spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    url: "jdbc:h2:./build/run"
    username: "kayvault"
    password: "password"
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: "update"

---

spring:
  config:
    activate:
      on-profile:
      - prod
  datasource:
    url: "jdbc:mariadb://db:3306/kayvaultdb"
    username: "kayvault"
    password: "password"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: "update"
